### ISSUE TITLE
Gosec 2.7.0

### ISSUE THREAD

**Issue by 030** [alexmurray/gosec-snap#1]
Could you update gosec to 2.7.0?

**Comment by alexmurray** [comment]
2.7.0 is already built and published to the edge channel, I will publish it to stable once I do some testing on it first this morning but if you want to give it a try and let me know if it works before then that'd be great.

**Comment by alexmurray** [comment]
2.7.0 is now published to the stable channel.

**Comment by 030** [comment]
I have installed 2.7.0, but it seems to be the same version as 2.6.1 as the issue persists.

**Comment by alexmurray** [comment]
What issue are you seeing?

**Comment by 030** [comment]
It seems that the gosec has not been updated well. The maintainer of gosec will have a look. Currently the go get still installs the 2.6.1.

**Comment by alexmurray** [comment]
Hmm perhaps I should change the snap to use the pre-built binaries instead of using `go get`

**Comment by 030** [comment]
@alexmurray I can confirm that the release 2.7.0 works in our CI.

**Comment by alexmurray** [comment]
I have changed the snap to just repackage the upstream binaries so this should be identical to the upstream release *but then be confined as per the usual snap strict confinement model. This does for now limit the snap to being only available on amd64 however which is a shame but currently the snap only has users on amd64 as far as I am aware so this shouldn't actually affect any existing users.
